version: '3'
services:
  postgres-server:
    image: postgres:9.6-alpine
    container_name: barefoot-nomad-db
    environment:
      - "POSTGRES_USER=${DB_USER_NAME}"
      - "POSTGRES_DB=${DB_DEV_NAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - PGDATA=/var/lib/postgresql/data/pg9.6
    ports:
      - "5432:5432"

  api:
    container_name: barefoot-nomad-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres-server
    volumes:
      - /usr/barefoot-nomad-backend/node_modules
      - .:/usr/barefoot-nomad-backend
