# base image
FROM node:latest
LABEL AUTHOR="Arnold Katumba <arnold.katumba@andela.com>"

# set working directory
WORKDIR /usr/barefoot-nomad-backend

# copy package.json
COPY ./package.json .

# install and cache app dependencies
RUN npm i

# add app
COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
