# base image
FROM node:latest
LABEL AUTHOR="Arnold Katumba <arnold.katumba@andela.com>"

# set working directory
WORKDIR /usr/barefoot-nomad-backend

# copy package.json
COPY ./package.json .

# install and cache app dependencies
RUN npm i
RUN npm i sequelize-cli@^5.5.1 -g
RUN npm i nodemon@^2.0.1 -g
RUN npm i nyc -g

# add app
COPY . .
# Expose the api port
EXPOSE 3000

# Start server
CMD ["npm", "run", "start:dev"]
